### PR TITLE
Allow custom document styles to be set

### PR DESCRIPTION
**Pull request by colinjeanne**
Word document styles are XML strings written to the DocX archive. Currently officegen uses a default set of styles and doesn't allow styles to be set on individual paragraphs. This exposes both a `styleXML` option when creating the document which takes an XML string to use a the set of document styles as well as a `pStyleDef` option on paragraphs to choose a style to apply to the paragraph.

### CODE REVIEW

**Comment by ellieejlee** [comment]
Hi @colinjeanne thank you for your reply. Would you be able to give me an example of how the custom styles are set? 

This does not seem to work: 
`var pObj = docx.createP();
pObj.addText('Table of Contents', { font_size: 16, color: '3a539b', font_face: 'Calibri (Headings)', w:name="heading 1" });`

**Comment by colinjeanne** [comment]
@ellieejlee, I went for the simplest possible implementation for this because doing something richer can get quite complex. The stylesheet is really just an XML string ([like this one](https://github.com/Ziv-Barber/officegen/pull/259/files#diff-07e818feceb3710adbf23431a7f79fa5R56)). The format is rather complex and I don't pretend to understand it but the way I generate my styles is to first create a Word document with the styles that I want, rename that file from .docx to .zip, open the zip, and copy out the `styles.xml` file. I have found http://www.datypic.com/sc/ooxml/s-wml.xsd.html to be a good enough reference as well for trying to refine the styles.

Once you have this string you can pass it in as a parameter when you create `officegen`. For example

```
const docx = officegen({
  type: 'docx',
  title: 'My Document',
  styleXML,
});
```

You can apply a style by name using the `pStyleDef` option. For example

```
const p = docx.createP({
  pStyleDef: 'Heading1',
});
```

**Comment by jonasfrid** [comment]
@colinjeanne I can't seem to create a paragraph with Heading1 using your example.
I am successfully importing the styles.xml, and creating a docx, but it gets the basic paragraph style.

Code snippet for reference:
```
officegen.setVerboseMode(false);
  // test
  let docx = officegen({
    type: 'docx',
    title,
    styleXML
  });

  docx.createP({
    pStyleDef: 'Heading1',
  }).addText(`Heading #1`);
  docx.createP({
    backline: 'E0E0E0'
  }).addText('Content #1');
  docx.createP({
    pStyleDef: 'Heading1'
  }).addText('Heading #2', { pStyleDef: 'heading 1', style: 'Heading1' });
```

Attaching the styles + generated docx.

[styles-and-docx.zip](https://github.com/Ziv-Barber/officegen/files/3223700/styles-and-docx.zip)

**Comment by suhaig** [comment]
I think it's a bug. `pStyleDef` is only applied if `pPrData` is [falsy](https://github.com/Ziv-Barber/officegen/blob/d1d47cd7b5176c6385fe73d799d659d59549f150/lib/docx/gendocx.js#L265). But `pPrData` is never falsy if the paragraph has any [option](https://github.com/Ziv-Barber/officegen/blob/d1d47cd7b5176c6385fe73d799d659d59549f150/lib/docx/gendocx.js#L216). And `pStyleDef` is an option of the paragraph.

**Comment by Ziv-Barber** [comment]
> 
> 
> I think it's a bug. `pStyleDef` is only applied if `pPrData` is [falsy](https://github.com/Ziv-Barber/officegen/blob/d1d47cd7b5176c6385fe73d799d659d59549f150/lib/docx/gendocx.js#L265). But `pPrData` is never falsy if the paragraph has any [option](https://github.com/Ziv-Barber/officegen/blob/d1d47cd7b5176c6385fe73d799d659d59549f150/lib/docx/gendocx.js#L216). And `pStyleDef` is an option of the paragraph.

I already have a fix for this. It'll be in the next version (0.6.3).

**Comment by illiphilli** [comment]
Hi,

I see that this has been merged, but I can't find any examples of how this should be implemented.

The example shows how it will be implemented, but there's the [comment](https://github.com/Ziv-Barber/officegen/blob/HEAD/examples/make_docx.js#L15) stating that it isn't working yet...

Any feedback on this?

**Comment by ddumond** [comment]
for anyone else looking for this, I found the answer here: https://github.com/Ziv-Barber/officegen/issues/257#issuecomment-802955540

**Pull request merged**
