### PR TITLE
Add line chart + examples

### PR DESCRIPTION
**Pull request by AlexMoroz**

### CODE REVIEW

**Comment by saravmajestic** [comment]
Hi Alex,

Great addition to the library! 

One issue i can see in line graph is, the tooltips are not working as expected with sample code. On hovering the data points, its not showing tooltips. Do you have any solution for this? Please let me know if you need more info.
[out.pptx](https://github.com/Ziv-Barber/officegen/files/405294/out.pptx)

**Comment by AlexMoroz** [comment]
Hi @saravmajestic,

The tooltips work fine. I can't see any difference between the line chart created by officegen and the one created with the powerpoint.

screen shot 2016-08-07 at 11 53 26

**Comment by saravmajestic** [comment]
Hi @AlexMoroz ,

I meant the tooltip on hover of the data point as in screenshot.

The tooltip shows for a datapoint in blue series, but I actually hovered on red series data point. I couldnt see correct tool tip for particular datapoint and it does not show tooltips for red series.

Do you also face this issue?

Thanks for checking out!

screen shot 2016-08-07 at 3

**Comment by AlexMoroz** [comment]
It seems like I don't have this issue. 

This is how the tooltips work for me. Can't see any problem.

tooltip

**Comment by AlexMoroz** [comment]
I will create a new pull-request later.

**Pull request closed without merging**
