### PR TITLE
adding support for header/footer

### PR DESCRIPTION
**Pull request by jfairley**
A while back I started on work for https://github.com/Ziv-Barber/officegen/issues/52. As is, this works, but the ability to left-, center-, or right-align content doesn't seem to be working right. Everything is left-justified and space-delimited. I had intended to get back to this and finish it, but apparently I haven't been able to get to it, so it is what it is. :grinning:

### CODE REVIEW

**Comment by jfairley** [comment]
@Ziv-Barber 
If you'd like me to PR this into a different branch, let me know.

**Comment by jchabot86** [comment]
so is this feature available if i install from npm?

**Comment by kickthedragon** [comment]
unfortunately it isn't available yet since it was never merged into the master repository.  It would be great if someone completed, and included implementing page numbers as well.

**Comment by Ziv-Barber** [comment]
I'll work on the header-footer after finishing the first implementation of
the pptx slides layouts.

**Comment by jfairley** [comment]
@Ziv-Barber is it appropriate for me to close this? Thanks for your work on #52. I'll have to check it out some time!

**Pull request closed without merging**
